server:
  port: 8761
spring:
  application:
    name: sim-service-registry
management:
  endpoint:
    health:
      show-details: always
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${ENVIRONMENT_SERVICE_REGISTRY:http://localhost:8761/eureka/}
  instance:
    hostname: ${CLUSTER_SERVICE_REGISTRY:localhost}
    preferIpAddress: false
    nonSecurePort: 80